version: 2
updates:
  - package-ecosystem: "gradle"
    directory: |
      - "/Minix-Platform"
      - "/Minix-Gradle"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"