name: Dependency update check

on:
  pull_request:
    branches: [ main ]
    paths: [ "**.toml", "**.gradle.kts", "catalog.yml" ]
  push:
    branches: [ main ]
    paths: [ "**.toml", "**.gradle.kts", "catalog.yml" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run validate-dependencies task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean :catalog:validate-dependencies

      - name: Upload final catalog
        uses: actions/upload-artifact@v3
        with:
          name: catalog.toml
          path: build/catalog/version-catalog/libs.versions.toml
          if-no-files-found: error
