name: Docs

on:
  push:
    branches: [ main ]
    paths: [ "Minix-Gradle", "Minix-NMS", "minix-plugin", "gradle.properties", ".github/workflows/docs.yml" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean :Minix-Gradle:docs :Minix-NMS:docs :minix-plugin:docs

      - name: Build Docs
        run: ./gradlew dokkaHtmlMultiModule --info

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          keep_files: true
          full_commit_message: 'docs: Publish documentation'
