name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "./**.gradle.kts", "Minix-Gradle/**", "gradle.properties", ".github/workflows/gradle-ci.yml", "gradle/wrapper/**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/wrapper-validation.yml

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :Minix-Gradle:build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/minix-gradle/libs/

  publish:
    needs: build
    if: github.event_name == 'push'
    uses: ./.github/workflows/publish.yml
