name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    paths: [ "./**.gradle.kts", "Minix-Gradle", "Minix-NMS", "gradle.properties", ".github/workflows/gradle-ci.yml", "gradle", "catalog" ] # TODO: Remove catalog and have it publish its own artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: ./gradlew clean build

      - name: Extract Current Branch name
        shell: bash
        # bash pattern expansion to grab branch name without slashes
        run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
        id: ref

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ steps.ref.outputs.branch }}
          path: build/libs

      - name: Publish to repo
        run: ./gradlew publish -PRacciRepoUsername=${{ secrets.REPO_PUBLISH_USERNAME }} -PRacciRepoPassword=${{ secrets.REPO_PUBLISH_PASSWORD }}
