name: Gradle plugin CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "./**.gradle.kts", "gradle/**", "minix-plugin/**", "gradle.properties", ".github/workflows/gradle-plugin-ci.yml" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/wrapper-validation.yml

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :minix-plugin:build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/minix-plugin/
          if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :minix-plugin:check

  publish:
    needs: [ build, test ]
    if: github.event_name == 'push'
    uses: ./.github/workflows/publish.yml
    secrets: inherit