name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    paths: [ "./**.gradle.kts", "Minix-Gradle/**", "Minix-NMS/**", "gradle.properties", ".github/workflows/gradle-ci.yml", "gradle/**", "catalog/**" ] # TODO: Remove catalog and have it publish its own artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clean, build, and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build test

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs

  publish:
    needs: build
    uses: ./.github.workflows/publish.yml@main
