name: Gradle plugin CI

on:
  push:
    branches: [ main ]
    paths: [ "./**.gradle.kts", "gradle", "minix-plugin", "gradle.properties", ".github/workflows/gradle-plugin-ci.yml" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: ./gradlew clean :minix-plugin:build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ steps.ref.outputs.branch }}
          path: build/libs/minix-plugin/
