name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Run detekt
        run: ./gradlew detektMain

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/libs

      - name: Publish to repo
        run: ./gradlew publish -PRacciRepoUsername=${{ secrets.REPO_PUBLISH_USERNAME }} -PRacciRepoPassword=${{ secrets.REPO_PUBLISH_PASSWORD }}

      - name: Check whether the gradle platform has been updated
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            platform:
              - 'Minix-Platform/**'

      - name: Get version from gradle
        if: steps.changes.outputs.platform == 'true'
        shell: bash
        id: extract_version
        run: |
          version=`./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}'`
          echo "::set-output name=version::$version"

      - name: Create GitHub Release for shaded Minix Platfrom
        if: steps.changes.outputs.platform == 'true'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
          files: |
            Minix-Platform/shaded/build/libs/*.platform
