name: NMS-CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "Minix-NMS/**", "gradle.properties", ".github/workflows/nms-ci.yml" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/wrapper-validation.yml

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Execute Gradle action
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :nms:assemble

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/nms/libs/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Execute Gradle action
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :nms:check

  publish:
    needs: [ build, test ]
    if: github.event_name == 'push'
    uses: ./.github/workflows/publish.yml
    secrets: inherit
