name: NMS-CI

on:
  workflow_call:
  push:
    branches: [ main ]
    paths: [ "Minix-NMS/**", "gradle.properties", ".github/workflows/nms-ci.yml" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/wrapper-validation.yml

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: &checkout actions/checkout@v3

      - uses: &setup actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: &gradle gradle/gradle-build-action@v2
        name: Execute Gradle action
        with:
          arguments: :Minix-NMS:build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: *checkout
      - uses: *setup

      - uses: *gradle
        with:
          arguments: :Minix-NMS:check

  publish:
    needs: [ build, test ]
    if: github.event_name == 'push'
    uses: ./.github/workflows/publish.yml

