name: Publish to Repository

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Publish to Repository
        uses: gradle/gradle-build-action@v2
        env:
          RacciRepoUsername: ${{ secrets.REPO_PUBLISH_USERNAME }}
          RacciRepoPassword: ${{ secrets.REPO_PUBLISH_PASSWORD }}
        with:
          arguments: publish

  docs:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build docs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean dokkaHtmlMultiModule

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          keep_files: true
          full_commit_message: 'docs: Publish documentation'
