name: Validate Gradle Wrapper
on: [workflow_call, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: gradle/wrapper-validation-action@v2.1.2