name: Validate Gradle Wrapper
on: [workflow_call, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: gradle/wrapper-validation-action@v2.1.2