name: Validate Gradle Wrapper
on: [workflow_call, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: gradle/wrapper-validation-action@v1.1.0